name: Frederick's Perch
baseurl: fredchan.org
permalink: /blog/:title:output_ext

description: The website and portfolio of Frederick Chan, Software Engineer and Technomancer from the Emerald City

plugins:
  - jekyll-postcss

postcss:
  cache: false