name: Frederick's Perch
permalink: /blog/:title/

description: The website and portfolio of Frederick Chan, Software Engineer and Technomancer from the Emerald City

plugins:
  - jekyll-postcss

postcss:
  cache: false